Repository 2024-Summer-BootCamp-TeamK/Frontend, pull requests merged in 2024-07, with the labels that each got.

#4 메인페이지,ai리뷰결과페이지,파일업로드페이지,공유화면파일업로드페이지,url링크접속페이지
  package-lock.json
  package.json
  public/Logo.jsx
  src/App.jsx
  src/components/ Modificationsuggestion.jsx
  src/components/Aireviewresult.jsx
  src/components/Button.jsx
  src/components/Buttonall.jsx
  src/components/Header.jsx
  src/components/Headerall.jsx
  src/components/Mycomponents.jsx
  src/components/Orangebutton.jsx
  src/components/Popupkeycreate.jsx
  src/images/aireviewed.svg
  src/images/arrow.svg
  src/images/logo.svg
  src/images/main1-1.svg
  src/images/main1-2.svg
  src/images/main1-3.svg
  src/images/main1.svg
  src/images/main2-1.svg
  src/images/main2-2.svg
  src/images/main2-3.svg
  src/images/main2.svg
  src/images/mainend.svg
  src/images/upload.svg
  src/index.css
  src/main.jsx
  src/pages/Fileupload.jsx
  src/pages/Fileuploadshare.jsx
  src/pages/Mainpage.jsx
  src/pages/Reviewresult.jsx
  src/pages/Urlentrance.jsx
Labels: 디자인

#5 Design/#3 카테고리 페이지
  package-lock.json
  src/App.jsx
  src/components/button.jsx
  src/images/file.png
  src/images/logo.png
  src/index.css
  src/pages/Category.jsx
Labels: 디자인

#12 Design/설명팝업창, 카테고리 페이지 구현
  package-lock.json
  package.json
  src/App.jsx
  src/components/Button.jsx
  src/components/Card.jsx
  src/components/Header.jsx
  src/components/Popupexlain.jsx
  src/components/Popupkeycreate.jsx
  src/components/button.jsx
  src/images/explain1.svg
  src/pages/C.jsx
  src/pages/Category.jsx
  src/pages/Mainpage.jsx
Labels: 디자인

#19 design 비밀번호,이메일 페이지
  src/components/Popupkeycreate.jsx
  src/components/Popupkeyinput.jsx
Labels: 디자인

#25 Design#22/ 카테고리, key팝업창 수정
  .eslintrc.cjs
  src/App.jsx
  src/components/ Modificationsuggestion.jsx
  src/components/Popupkeycreate.jsx
  src/components/Popupkeyinput.jsx
  src/components/Suggestion.jsx
  src/components/Toggleswitch.jsx
  src/pages/Carousel.jsx
  src/pages/Category.jsx
  src/pages/Resultcompare.jsx
  src/pages/Reviewresult.jsx
Labels: 디자인

#27 design/ 검토결과 수정 진행중!
  src/components/Popupkeycreate.jsx
  src/components/Popupkeyinput.jsx
  src/components/Toggleswitch.jsx
  src/images/Eye_off.svg
  src/images/Eye_on.svg
  src/pages/Category.jsx
  src/pages/Reviewresult.jsx
Labels: 디자인

#29 mainpage retouch
  src/components/Orangebutton.jsx
  src/images/main1-2.svg
  src/images/mainend.svg
  src/pages/Mainpage.jsx
Labels: 디자인

#31 #28 feat 파일 업로드 API 연동
  .eslintrc.cjs
  package-lock.json
  package.json
  src/components/Popupkeycreate.jsx
  src/components/ReviewStartButtonComponent.jsx
  src/pages/Category.jsx
  src/pages/Fileupload.jsx
  src/pages/Fileuploadshare.jsx
  src/pages/Key.jsx
  src/services/fileupload_API.jsx
  src/services/share_API.jsx
Labels: 기능구현

#37 design 메인페이지 ui수정
  src/App.jsx
  src/components/Button.jsx
  src/components/Buttonall.jsx
  src/components/Header.jsx
  src/components/Headerall.jsx
  src/components/Orangebutton.jsx
  src/components/Popupkeycreate.jsx
  src/images/main1-2.svg
  src/images/main1-3.svg
  src/images/main2-2.svg
  src/images/main2-3.svg
  src/pages/Mainpage.jsx
  src/pages/Urlentrance.jsx
Labels: 디자인

#40 [Feat!/#38] 마우스 포인터, 페이지 인덱스, 서명 삽입 공유 완료
  src/App.jsx
  src/components/PdfEditorComponent/MenuBar.tsx
  src/components/PdfEditorComponent/Page.tsx
  src/components/Popupkeyinput.jsx
  src/components/modals/DrawingModal.tsx
  src/containers/Drawing.tsx
  src/index.css
  src/pages/Keyinput.jsx
  src/pages/PdfEditor.jsx
  src/services/access_API.jsx
  src/services/pdfService.jsx
Labels: 기능구현

#46 [45 feat] 수정하기 버튼 api연동 완료
  package-lock.json
  src/components/Suggestion.jsx
  src/services/updateContractService.jsx
Labels: 기능구현

#51 suggestion page의 수정안 추가 확인 메세지
  src/components/Suggestion.jsx
Labels: 기능구현

#63 design / 메인페이지 텍스트 애니메이션 추가
  package-lock.json
  package.json
  src/components/Button.jsx
  src/components/Header.jsx
  src/components/Textanimation.jsx
  src/components/button.jsx
  src/images/layer1.svg
  src/images/layer2.svg
  src/images/main1.svg
  src/pages/Mainpage.jsx
  vite.config.js
Labels: 디자인

#72 feat / 버튼 navigate 연동
  src/pages/Carousel.jsx
  src/pages/Category.jsx
  src/pages/Fileupload.jsx
  src/pages/Fileuploadshare.jsx
  src/pages/Key.jsx
  src/pages/Keyinput.jsx
  src/pages/Loading.jsx
  src/pages/Mainpage.jsx
Labels: 기능구현

#77 로컬스토리지에서 sessoinStorage로 변경
  src/components/Suggestion.jsx
Labels: 리팩토링, 기능구현

#82 pdf-editor 간격 맞춤
  src/pages/PdfEditor.jsx
Labels: 디자인

#81 Design/#79
  src/App.jsx
  src/components/Popupkeycreate.jsx
  src/components/Textanimation.jsx
  src/images/main1.svg
  src/pages/Fileupload.jsx
  src/pages/Key.jsx
  src/pages/Mainpage.jsx
Labels: 디자인

#84 design / 폰트적용
  package-lock.json
  src/App.jsx
  src/components/Button.jsx
  src/components/button.jsx
  src/images/main1.svg
  src/pages/Category.jsx
Labels: 디자인

#87 pdf에디터 간격 수정 완료
  src/pages/PdfEditor.jsx
Labels: 디자인

#88 85 design 메인페이지 디자인 고도화 + 파일업로드 페이지
  src/components/Card.jsx
  src/components/Orangebutton.jsx
  src/components/UseIntersectionObserver.jsx
  src/pages/Category.jsx
  src/pages/Fileupload.jsx
  src/pages/Fileuploadshare.jsx
  src/pages/Mainpage.jsx
Labels: 디자인

#94 reviewresult, fileupload,key페이지 로딩 추가 및 헤더 로고크기 수정
  src/components/Popuploading.jsx
  src/components/Suggestion.jsx
  src/pages/Fileupload.jsx
  src/pages/Fileuploadshare.jsx
  src/pages/Loading.jsx
  src/pages/PdfEditor.jsx
Labels: 기능구현, 디자인

#97 89 design 메인페이지 텍스트 애니메이션 변경
  index.html
  src/components/Popupkeycreate.jsx
  src/images/icon.png
  src/pages/Key.jsx
  src/pages/Mainpage.jsx
Labels: 디자인

#101 design / 메인페이지 수정
  src/components/Aireviewresult2.jsx
  src/components/Orangebutton.jsx
  src/images/main1.svg
  src/pages/Mainpage.jsx
Labels: 디자인

#103 design / 메인텍스트 폰트 변경
  src/images/main1.svg
  src/pages/Loading.jsx
  src/pages/Mainpage.jsx
Labels: 디자인

#105 headerall(네비게이트 연결), 팝업에 계약서 아이디 뜨는거 삭제
  src/components/Header.jsx
  src/components/Headerall.jsx
  src/pages/Carousel.jsx
  src/pages/Category.jsx
  src/pages/Fileupload.jsx
  src/pages/Fileuploadshare.jsx
  src/pages/Key.jsx
  src/pages/Keyinput.jsx
  src/pages/Loading.jsx
  src/pages/PdfEditor.jsx
  src/pages/Resultcompare.jsx
  src/pages/Reviewresult.jsx
Labels: 기능구현

#107 design/ 최종 마무리
  src/components/ReviewStartButtonComponent.jsx
  src/images/main1.svg
  src/pages/Category.jsx
  src/pages/Mainpage.jsx
Labels: 디자인
